name: Docker Image CI
on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        if: success()
        run: docker build . --file Dockerfile --tag test-github-ci:$(date +%s)
